# Generated by Django 3.2.4 on 2021-08-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=14)),
                ('age', models.PositiveSmallIntegerField()),
                ('nationality', models.CharField(max_length=20)),
                ('trainer_image', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('Date_of_Birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=12)),
                ('subject_name', models.CharField(max_length=20)),
                ('national_id', models.CharField(max_length=12)),
                ('salary', models.PositiveBigIntegerField()),
                ('phone_number', models.CharField(max_length=12)),
                ('job_title', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=12)),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
    ]
