# Generated by Django 3.2.4 on 2021-09-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='trainer_image',
            new_name='image',
        ),
    ]
