# Generated by Django 3.2.4 on 2021-08-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=12)),
                ('course_code', models.CharField(max_length=6)),
                ('trainer_id', models.CharField(max_length=10)),
                ('course_description', models.CharField(max_length=16)),
                ('course_channel', models.CharField(max_length=16)),
                ('course_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
