# Generated by Django 3.2.4 on 2021-08-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(choices=[('k', 'Kenyan'), ('u', 'Ugandan'), ('R', 'Rwandan'), ('S', 'Sudanese'), ('S', 'SouthSudanese')], max_length=20)),
                ('image_of_student', models.ImageField(blank=True, null=True, upload_to='')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('m', 'Male'), ('O', 'Other')], max_length=16)),
                ('subject', models.CharField(blank=True, max_length=30, null=True)),
                ('health_records', models.FileField(upload_to='')),
                ('class_room', models.CharField(blank=True, max_length=16, null=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('gurdian_name', models.CharField(max_length=20)),
                ('gurdian_contact', models.CharField(max_length=12)),
                ('parent_name', models.CharField(max_length=20)),
                ('parent_contact', models.CharField(max_length=12)),
                ('passport', models.CharField(max_length=20)),
                ('academic_year', models.DateField(blank=True, max_length=8, null=True)),
                ('admission_date', models.DateField(blank=True, max_length=16, null=True)),
                ('languages', models.CharField(choices=[('E', 'English'), ('K', 'Kiswahili'), ('F', 'French')], max_length=15)),
            ],
        ),
    ]
