# Generated by Django 3.2.4 on 2021-09-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210817_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='image_of_student',
            new_name='image',
        ),
    ]
